# Generated by Django 5.2.8 on 2026-08-09 15:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=10)),
                ('rule_id', models.CharField(default='UNKNOWN_RULE', max_length=20)),
                ('message', models.TextField(default='No message')),
                ('uri', models.CharField(max_length=2048)),
                ('referer', models.CharField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(default='Detected', max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.IntegerField(default=2)),
                ('anomaly_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CrsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('published_at', models.DateTimeField()),
                ('zip_url', models.URLField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.CharField(max_length=20)),
                ('cpu_load', models.CharField(max_length=20)),
                ('ram_usage', models.CharField(max_length=20)),
                ('disk_usage', models.CharField(max_length=20)),
                ('storage_free', models.CharField(max_length=20)),
                ('total_processes', models.CharField(max_length=20)),
                ('total_threads', models.CharField(max_length=20)),
                ('total_handles', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
