# Generated by Django 5.2.8 on 2026-08-09 15:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wafinstaller", "0002_add_audit_entry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z][A-Za-z0-9_.-]{1,79}$",
                                "Use 2-80 letters, numbers, dots, underscores or hyphens.",
                            )
                        ],
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("trusted", "Trusted (inspect, never auto-ban)"),
                            ("waf_bypass", "WAF bypass"),
                            ("block", "Block"),
                            ("observe", "Observe only"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_waf_address_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="RuleExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("remove_rule", "Remove rule"),
                            ("remove_target", "Remove variable from rule"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rule_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("rule_tag", models.CharField(blank=True, max_length=120)),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        help_text="For example ARGS:description. Required for target exclusions.",
                        max_length=255,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=253)),
                ("path", models.CharField(blank=True, max_length=2048)),
                (
                    "path_match",
                    models.CharField(
                        choices=[("exact", "Exact path"), ("prefix", "Path prefix")],
                        default="prefix",
                        max_length=12,
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=12)),
                ("rationale", models.CharField(max_length=1000)),
                ("owner", models.CharField(max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_waf_rule_exclusions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AddressEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network", models.CharField(max_length=49)),
                ("comment", models.CharField(max_length=500)),
                ("source", models.CharField(default="manual", max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_waf_address_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "address_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="wafinstaller.addresslist",
                    ),
                ),
            ],
            options={
                "ordering": ("address_list__name", "network"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("address_list", "network"),
                        name="unique_network_per_waf_address_list",
                    )
                ],
            },
        ),
    ]
