# Generated by Django 5.2.8 on 2026-08-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wafinstaller", "0005_application_configrevision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attack",
            name="destination_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attack",
            name="destination_port",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attack",
            name="protocol",
            field=models.CharField(default="TCP", max_length=8),
        ),
        migrations.AddField(
            model_name="attack",
            name="source_port",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
