import fcntl
import os
import stat
import subprocess
import tempfile
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path

from django.conf import settings
from django.utils import timezone

from wafinstaller.helper.adapters import get_paths
from wafinstaller.models import (
    AddressList,
    Policy,
    PolicyBinding,
    RuleExclusion,
)

BEFORE_FILENAME = "REQUEST-890-WAFCONTROL-BEFORE.conf"
AFTER_FILENAME = "RESPONSE-990-WAFCONTROL-AFTER.conf"


class PolicyDeploymentError(RuntimeError):
    """Raised when generated policy files cannot be deployed safely."""


@dataclass(frozen=True)
class PolicyBundle:
    before: str
    after: str
    active_exclusions: int
    active_address_entries: int
    warnings: tuple[str, ...]
    active_applications: int = 0


def _header(position: str) -> list[str]:
    return [
        "# Generated by WAFControl. Do not edit this file manually.\n",
        f"# Position: {position}.\n\n",
    ]


def _render_address_lists(
    address_lists: Iterable[AddressList], moment
) -> tuple[list[str], int, list[str]]:
    lines: list[str] = []
    active_count = 0
    warnings: list[str] = []
    for address_list in address_lists:
        networks = [
            entry.network
            for entry in address_list.entries.all()
            if entry.is_active_at(moment)
        ]
        if not address_list.enabled or not networks:
            continue
        active_count += len(networks)
        joined = ",".join(sorted(networks))
        lines.append(
            f"# Address list: {address_list.name} ({address_list.get_purpose_display()})\n"
        )
        if address_list.purpose == AddressList.Purpose.TRUSTED:
            lines.append(
                "# Trusted semantics: retain WAF inspection; export to Fail2ban/CrowdSec later.\n\n"
            )
            continue

        rule_id = 1_600_000 + address_list.pk
        if rule_id > 1_699_999:
            raise PolicyDeploymentError("Address-list identifier range is exhausted.")
        if address_list.purpose == AddressList.Purpose.WAF_BYPASS:
            actions = f"id:{rule_id},phase:1,pass,nolog,ctl:ruleEngine=Off"
            warnings.append(
                f"{address_list.name} disables WAF inspection for {len(networks)} network(s)."
            )
        elif address_list.purpose == AddressList.Purpose.BLOCK:
            actions = (
                f"id:{rule_id},phase:1,deny,status:403,log,"
                f"msg:'WAFControl block list {address_list.name}'"
            )
        else:
            actions = (
                f"id:{rule_id},phase:1,pass,log,"
                f"msg:'WAFControl observe list {address_list.name}'"
            )
        lines.append(f'SecRule REMOTE_ADDR "@ipMatch {joined}" "{actions}"\n\n')
    return lines, active_count, warnings


def _exclusion_action(exclusion: RuleExclusion) -> str:
    selector = (
        f"ById={exclusion.rule_id}"
        if exclusion.rule_id
        else f"ByTag={exclusion.rule_tag}"
    )
    if exclusion.kind == RuleExclusion.Kind.REMOVE_TARGET:
        return f"ctl:ruleRemoveTarget{selector};{exclusion.target}"
    return f"ctl:ruleRemove{selector}"


def _scope_conditions(exclusion: RuleExclusion) -> list[tuple[str, str]]:
    conditions: list[tuple[str, str]] = []
    if exclusion.host:
        conditions.append(("REQUEST_HEADERS:Host", f"@streq {exclusion.host.lower()}"))
    if exclusion.path:
        operator = (
            "@streq"
            if exclusion.path_match == RuleExclusion.PathMatch.EXACT
            else "@beginsWith"
        )
        conditions.append(("REQUEST_URI", f"{operator} {exclusion.path}"))
    if exclusion.method:
        conditions.append(("REQUEST_METHOD", f"@streq {exclusion.method}"))
    return conditions


def _render_scoped_exclusion(exclusion: RuleExclusion) -> list[str]:
    conditions = _scope_conditions(exclusion)
    generated_id = 1_700_000 + exclusion.pk
    if generated_id > 1_799_999:
        raise PolicyDeploymentError("Rule-exclusion identifier range is exhausted.")

    action = f"id:{generated_id},phase:1,pass,nolog,{_exclusion_action(exclusion)}"
    if len(conditions) > 1:
        action += ",chain"

    variable, operator = conditions[0]
    lines = [
        f"# Exclusion: {exclusion.name}; owner={exclusion.owner}; rationale={exclusion.rationale}\n",
        f'SecRule {variable} "{operator}" "{action}"\n',
    ]
    for index, (variable, operator) in enumerate(conditions[1:], start=1):
        chained_action = "chain" if index < len(conditions) - 1 else "t:none"
        lines.append(f'    SecRule {variable} "{operator}" "{chained_action}"\n')
    lines.append("\n")
    return lines


def effective_policy_snapshot(bindings=None):
    if bindings is None:
        bindings = PolicyBinding.objects.select_related(
            "application", "policy", "policy__parent"
        ).all()
    applications = []
    for binding in bindings:
        if (
            not binding.enabled
            or not binding.application.enabled
            or not binding.policy.enabled
        ):
            continue
        applications.append(
            {
                "application_id": binding.application_id,
                "name": binding.application.name,
                "hostname": binding.application.hostname,
                "policy_id": binding.policy_id,
                "policy": binding.policy.name,
                "overrides": binding.overrides,
                "effective": binding.effective_config(),
            }
        )
    applications.sort(key=lambda item: (item["hostname"], item["application_id"]))
    return {"schema": 1, "applications": applications}


def _render_application_policies(bindings) -> tuple[list[str], int]:
    lines = []
    active_count = 0
    engine_actions = {
        Policy.EngineMode.OFF: "Off",
        Policy.EngineMode.DETECTION_ONLY: "DetectionOnly",
        Policy.EngineMode.ON: "On",
    }
    for item in effective_policy_snapshot(bindings)["applications"]:
        active_count += 1
        config = item["effective"]
        rule_id = 1_800_000 + item["application_id"]
        if rule_id > 1_899_999:
            raise PolicyDeploymentError("Application identifier range is exhausted.")
        actions = [
            f"id:{rule_id}",
            "phase:1",
            "pass",
            "nolog",
            f"ctl:ruleEngine={engine_actions[config['engine_mode']]}",
            f"setvar:tx.paranoia_level={int(config['paranoia_level'])}",
            f"setvar:tx.inbound_anomaly_score_threshold={int(config['inbound_threshold'])}",
            f"setvar:tx.outbound_anomaly_score_threshold={int(config['outbound_threshold'])}",
        ]
        lines.extend(
            [
                f"# Application: {item['name']}; policy={item['policy']}; host={item['hostname']}\n",
                f'SecRule REQUEST_HEADERS:Host "@streq {item["hostname"]}" "{",".join(actions)}"\n\n',
            ]
        )
    return lines, active_count


def render_policy(
    *,
    exclusions: Iterable[RuleExclusion] | None = None,
    bindings: Iterable[PolicyBinding] | None = None,
    address_lists: Iterable[AddressList] | None = None,
    moment=None,
) -> PolicyBundle:
    moment = moment or timezone.now()
    if exclusions is None:
        exclusions = RuleExclusion.objects.all()
    if address_lists is None:
        address_lists = AddressList.objects.prefetch_related("entries").all()
    if bindings is None:
        bindings = PolicyBinding.objects.select_related(
            "application", "policy", "policy__parent"
        ).all()

    before = _header("before CRS")
    after = _header("after CRS")
    address_lines, address_count, warnings = _render_address_lists(
        address_lists, moment
    )
    application_lines, application_count = _render_application_policies(bindings)
    before.extend(application_lines)
    before.extend(address_lines)

    active_exclusions = 0
    for exclusion in exclusions:
        if not exclusion.is_active_at(moment):
            continue
        active_exclusions += 1
        conditions = _scope_conditions(exclusion)
        if conditions:
            before.extend(_render_scoped_exclusion(exclusion))
        else:
            selector = exclusion.rule_id or exclusion.rule_tag
            selector_type = "Id" if exclusion.rule_id else "Tag"
            if exclusion.kind == RuleExclusion.Kind.REMOVE_TARGET:
                directive = (
                    f"SecRuleUpdateTargetBy{selector_type} {selector} "
                    f'"!{exclusion.target}"'
                )
            else:
                directive = f"SecRuleRemoveBy{selector_type} {selector}"
            after.extend(
                [
                    f"# Exclusion: {exclusion.name}; owner={exclusion.owner}; rationale={exclusion.rationale}\n",
                    f"{directive}\n\n",
                ]
            )

    return PolicyBundle(
        before="".join(before),
        after="".join(after),
        active_exclusions=active_exclusions,
        active_address_entries=address_count,
        active_applications=application_count,
        warnings=tuple(warnings),
    )


def policy_directory() -> Path:
    return Path(settings.WAFCONTROL_POLICY_DIR).resolve()


def policy_files(base_dir: Path | None = None) -> tuple[Path, Path]:
    base = (base_dir or policy_directory()).resolve()
    return base / BEFORE_FILENAME, base / AFTER_FILENAME


def include_directives(base_dir: Path | None = None) -> tuple[str, str]:
    before, after = policy_files(base_dir)
    return f"Include {before}", f"Include {after}"


def include_status(base_dir: Path | None = None) -> bool:
    main_conf = Path(get_paths().modsec_conf).with_name("main.conf")
    try:
        content = main_conf.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return False
    return all(directive in content for directive in include_directives(base_dir))


def _atomic_write(path: Path, content: bytes, mode: int) -> None:
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.wafcontrol-", dir=str(path.parent)
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def deploy_policy_bundle(
    bundle: PolicyBundle,
    *,
    base_dir: Path | None = None,
    test_cmd: Sequence[str] | None = None,
    reload_cmd: Sequence[str] | None = None,
    require_includes: bool = True,
) -> bool:
    base = (base_dir or policy_directory()).resolve()
    if not base.is_dir():
        raise PolicyDeploymentError(f"Managed policy directory does not exist: {base}")
    if require_includes and not include_status(base):
        before_include, after_include = include_directives(base)
        raise PolicyDeploymentError(
            "Managed policy files are not wired into the ModSecurity configuration. "
            f"Add '{before_include}' before CRS rules and '{after_include}' after CRS rules."
        )

    before_path, after_path = policy_files(base)
    desired = {
        before_path: bundle.before.encode("utf-8"),
        after_path: bundle.after.encode("utf-8"),
    }
    for path in desired:
        if path.is_symlink():
            raise PolicyDeploymentError(
                "Managed policy files must not be symbolic links."
            )

    lock_descriptor = os.open(
        base / ".wafcontrol-policy.lock", os.O_CREAT | os.O_RDWR | os.O_NOFOLLOW, 0o600
    )
    with os.fdopen(lock_descriptor, "r+b") as lock_handle:
        fcntl.flock(lock_handle.fileno(), fcntl.LOCK_EX)
        previous = {
            path: (
                path.exists(),
                path.read_bytes() if path.exists() else b"",
                stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o640,
            )
            for path in desired
        }
        if all(
            existed and previous[path][1] == content
            for path, content in desired.items()
            for existed in [previous[path][0]]
        ):
            return False

        for path, content in desired.items():
            _atomic_write(path, content, previous[path][2])
        try:
            if test_cmd:
                subprocess.run(
                    list(test_cmd), check=True, capture_output=True, text=True
                )
            if reload_cmd:
                subprocess.run(
                    list(reload_cmd), check=True, capture_output=True, text=True
                )
        except (OSError, subprocess.CalledProcessError) as exc:
            for path, (existed, content, mode) in previous.items():
                if existed:
                    _atomic_write(path, content, mode)
                else:
                    path.unlink(missing_ok=True)
            if reload_cmd:
                try:
                    subprocess.run(
                        list(reload_cmd), check=False, capture_output=True, text=True
                    )
                except (OSError, subprocess.SubprocessError):
                    pass
            raise PolicyDeploymentError(
                "Policy validation or reload failed; all managed files were restored."
            ) from exc
    return True


def policy_diff(bundle: PolicyBundle, base_dir: Path | None = None) -> str:
    import difflib

    before_path, after_path = policy_files(base_dir)
    sections = []
    for path, desired in (
        (before_path, bundle.before),
        (after_path, bundle.after),
    ):
        try:
            current = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            current = ""
        sections.extend(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                desired.splitlines(keepends=True),
                fromfile=f"active/{path.name}",
                tofile=f"candidate/{path.name}",
            )
        )
    return "".join(sections)
